language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
before_script:
  - "bundle exec rake test_app"
script: "DISPLAY=:99.0 bundle exec rspec spec"
notifications:
  email:
    - peter@pero-ict.nl
matrix:
  allow_failures:
    - rvm: 2.0.0
branches:
  only:
    - master